export const calendarMonths = [
  {
    month: 11,
    year: 2020,
    surchargable: false,
    days: [
      {
        value: '2020-11-01T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-02T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-03T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-04T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-05T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-06T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-07T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-08T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-09T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-10T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-11T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-12T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-13T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-14T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-15T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-16T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-17T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-18T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-11-19T00:00:00.000+08:00',
        available: false,
        price: -30,
        localized_total_price: '-RM30',
        human_readable_price: '-30',
        show_price: false,
        surchargable: false,
        total_price: -30,
        rebatable: true
      },
      {
        value: '2020-11-20T00:00:00.000+08:00',
        available: false,
        price: -30,
        localized_total_price: '-RM30',
        human_readable_price: '-30',
        show_price: false,
        surchargable: false,
        total_price: -30,
        rebatable: true
      },
      {
        value: '2020-11-21T00:00:00.000+08:00',
        available: false,
        price: -30,
        localized_total_price: '-RM30',
        human_readable_price: '-30',
        show_price: false,
        surchargable: false,
        total_price: -30,
        rebatable: true
      },
      {
        value: '2020-11-22T00:00:00.000+08:00',
        available: false,
        price: -30,
        localized_total_price: '-RM30',
        human_readable_price: '-30',
        show_price: false,
        surchargable: false,
        total_price: -30,
        rebatable: true
      },
      {
        value: '2020-11-23T00:00:00.000+08:00',
        available: false,
        price: -30,
        localized_total_price: '-RM30',
        human_readable_price: '-30',
        show_price: false,
        surchargable: false,
        total_price: -30,
        rebatable: true
      },
      {
        value: '2020-11-24T00:00:00.000+08:00',
        available: false,
        price: -30,
        localized_total_price: '-RM30',
        human_readable_price: '-30',
        show_price: false,
        surchargable: false,
        total_price: -30,
        rebatable: true
      },
      {
        value: '2020-11-25T00:00:00.000+08:00',
        available: true,
        price: -30,
        localized_total_price: '-RM30',
        human_readable_price: '-30',
        show_price: true,
        surchargable: false,
        total_price: -30,
        rebatable: true
      },
      {
        value: '2020-11-26T00:00:00.000+08:00',
        available: true,
        price: -30,
        localized_total_price: '-RM30',
        human_readable_price: '-30',
        show_price: true,
        surchargable: false,
        total_price: -30,
        rebatable: true
      },
      {
        value: '2020-11-27T00:00:00.000+08:00',
        available: true,
        price: -30,
        localized_total_price: '-RM30',
        human_readable_price: '-30',
        show_price: true,
        surchargable: false,
        total_price: -30,
        rebatable: true
      },
      {
        value: '2020-11-28T00:00:00.000+08:00',
        available: true,
        price: -30,
        localized_total_price: '-RM30',
        human_readable_price: '-30',
        show_price: true,
        surchargable: false,
        total_price: -30,
        rebatable: true
      },
      {
        value: '2020-11-29T00:00:00.000+08:00',
        available: true,
        price: -30,
        localized_total_price: '-RM30',
        human_readable_price: '-30',
        show_price: true,
        surchargable: false,
        total_price: -30,
        rebatable: true
      },
      {
        value: '2020-11-30T00:00:00.000+08:00',
        available: true,
        price: -30,
        localized_total_price: '-RM30',
        human_readable_price: '-30',
        show_price: true,
        surchargable: false,
        total_price: -30,
        rebatable: true
      }
    ]
  },
  {
    month: 12,
    year: 2020,
    surchargable: true,
    days: [
      {
        value: '2020-12-01T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-02T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-03T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-04T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-05T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-06T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-07T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-08T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-09T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-10T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-11T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-12T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-13T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-14T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-15T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-16T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-17T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-18T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-19T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-20T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-21T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-22T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-23T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-24T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2020-12-25T00:00:00.000+08:00',
        available: true,
        price: 100,
        localized_total_price: 'RM100',
        human_readable_price: '100',
        show_price: true,
        surchargable: true,
        total_price: 100,
        rebatable: false
      },
      {
        value: '2020-12-26T00:00:00.000+08:00',
        available: true,
        price: 100,
        localized_total_price: 'RM100',
        human_readable_price: '100',
        show_price: true,
        surchargable: true,
        total_price: 100,
        rebatable: false
      },
      {
        value: '2020-12-27T00:00:00.000+08:00',
        available: true,
        price: 100,
        localized_total_price: 'RM100',
        human_readable_price: '100',
        show_price: true,
        surchargable: true,
        total_price: 100,
        rebatable: false
      },
      {
        value: '2020-12-28T00:00:00.000+08:00',
        available: true,
        price: 100,
        localized_total_price: 'RM100',
        human_readable_price: '100',
        show_price: true,
        surchargable: true,
        total_price: 100,
        rebatable: false
      },
      {
        value: '2020-12-29T00:00:00.000+08:00',
        available: true,
        price: 100,
        localized_total_price: 'RM100',
        human_readable_price: '100',
        show_price: true,
        surchargable: true,
        total_price: 100,
        rebatable: false
      },
      {
        value: '2020-12-30T00:00:00.000+08:00',
        available: true,
        price: 100,
        localized_total_price: 'RM100',
        human_readable_price: '100',
        show_price: true,
        surchargable: true,
        total_price: 100,
        rebatable: false
      },
      {
        value: '2020-12-31T00:00:00.000+08:00',
        available: true,
        price: 100,
        localized_total_price: 'RM100',
        human_readable_price: '100',
        show_price: true,
        surchargable: true,
        total_price: 100,
        rebatable: false
      }
    ]
  },
  {
    month: 1,
    year: 2021,
    surchargable: false,
    days: [
      {
        value: '2021-01-01T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-02T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-03T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-04T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-05T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-06T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-07T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-08T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-09T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-10T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-11T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-12T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-13T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-14T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-15T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-16T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-17T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-18T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-19T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-20T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-21T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-22T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-23T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-24T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-25T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-26T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-27T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-28T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-29T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-30T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-01-31T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      }
    ]
  },
  {
    month: 2,
    year: 2021,
    surchargable: false,
    days: [
      {
        value: '2021-02-01T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-02T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-03T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-04T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-05T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-06T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-07T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-08T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-09T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-10T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-11T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-12T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-13T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-14T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-15T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-16T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-17T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-18T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-19T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-20T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-21T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-22T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-23T00:00:00.000+08:00',
        available: true,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-24T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-25T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-26T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-27T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      },
      {
        value: '2021-02-28T00:00:00.000+08:00',
        available: false,
        price: 0,
        localized_total_price: '',
        human_readable_price: '',
        show_price: false,
        surchargable: false,
        total_price: 0,
        rebatable: false
      }
    ]
  }
]

export const metaCalendarMonths = { surchargable: true, rebatable: true }

export const calTimeslots = [
  {
    value: '2020-12-25T07:00:00.000+08:00',
    available: true,
    price: -30,
    localized_total_price: '-RM90',
    human_readable_price: '-30',
    show_price: true,
    surchargable: false,
    total_price: -90,
    rebatable: true
  },
  {
    value: '2020-12-25T07:30:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T08:00:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T08:30:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T09:00:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T09:30:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T10:00:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T10:30:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T11:00:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T11:30:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T12:00:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T12:30:00.000+08:00',
    available: true,
    price: 60,
    localized_total_price: 'RM160',
    human_readable_price: '60',
    show_price: true,
    surchargable: true,
    total_price: 160,
    rebatable: false
  },
  {
    value: '2020-12-25T13:00:00.000+08:00',
    available: true,
    price: 60,
    localized_total_price: 'RM160',
    human_readable_price: '60',
    show_price: true,
    surchargable: true,
    total_price: 160,
    rebatable: false
  },
  {
    value: '2020-12-25T13:30:00.000+08:00',
    available: true,
    price: 60,
    localized_total_price: 'RM160',
    human_readable_price: '60',
    show_price: true,
    surchargable: true,
    total_price: 160,
    rebatable: false
  },
  {
    value: '2020-12-25T14:00:00.000+08:00',
    available: true,
    price: 60,
    localized_total_price: 'RM160',
    human_readable_price: '60',
    show_price: true,
    surchargable: true,
    total_price: 160,
    rebatable: false
  },
  {
    value: '2020-12-25T14:30:00.000+08:00',
    available: true,
    price: 60,
    localized_total_price: 'RM160',
    human_readable_price: '60',
    show_price: true,
    surchargable: true,
    total_price: 160,
    rebatable: false
  },
  {
    value: '2020-12-25T15:00:00.000+08:00',
    available: true,
    price: 60,
    localized_total_price: 'RM160',
    human_readable_price: '60',
    show_price: true,
    surchargable: true,
    total_price: 160,
    rebatable: false
  },
  {
    value: '2020-12-25T15:30:00.000+08:00',
    available: true,
    price: 60,
    localized_total_price: 'RM160',
    human_readable_price: '60',
    show_price: true,
    surchargable: true,
    total_price: 160,
    rebatable: false
  },
  {
    value: '2020-12-25T16:00:00.000+08:00',
    available: true,
    price: 0,
    localized_total_price: 'RM100',
    human_readable_price: '',
    show_price: false,
    surchargable: false,
    total_price: 100,
    rebatable: false
  },
  {
    value: '2020-12-25T16:30:00.000+08:00',
    available: true,
    price: 0,
    localized_total_price: 'RM100',
    human_readable_price: '',
    show_price: false,
    surchargable: false,
    total_price: 100,
    rebatable: false
  },
  {
    value: '2020-12-25T17:00:00.000+08:00',
    available: true,
    price: 0,
    localized_total_price: 'RM100',
    human_readable_price: '',
    show_price: false,
    surchargable: false,
    total_price: 100,
    rebatable: false
  },
  {
    value: '2020-12-25T17:30:00.000+08:00',
    available: true,
    price: 0,
    localized_total_price: 'RM100',
    human_readable_price: '',
    show_price: false,
    surchargable: false,
    total_price: 100,
    rebatable: false
  },
  {
    value: '2020-12-25T18:00:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T18:30:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T19:00:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T19:30:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T20:00:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T20:30:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T21:00:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T21:30:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T22:00:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T22:30:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  },
  {
    value: '2020-12-25T23:00:00.000+08:00',
    available: true,
    price: -10,
    localized_total_price: 'RM90',
    human_readable_price: '-10',
    show_price: true,
    surchargable: false,
    total_price: 90,
    rebatable: true
  }
]

export const metaCalTimeslots = { surchargable: true, rebatable: true }
